#!/usr/bin/bash
# Author: mivk (https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh)
# File: _is_ssh
# Description: Interal script to determine if the session is running through SSH
# Usage:
#	  Don't use it

function is_ssh() {
  p=${1:-$PPID}
  read pid name x ppid y < <( cat /proc/$p/stat )
  # or: read pid name ppid < <(ps -o pid= -o comm= -o ppid= -p $p) 
  [[ "$name" =~ sshd ]] && { echo "$(whoami) is connected through SSH : $pid $name"; return 0; }
  [ "$ppid" -le 1 ]     && { echo "$(whoami) is connected through a terminal : $pid $name";  return 1; }
  is_ssh $ppid
}

is_ssh $PPID
exit $?

