#!/usr/bin/bash
# Author: zent
# File: _log
# Description: Interal script to log other scripts
# Usage:
#	  Don't use it

PROGNAME=$(basename $(caller | awk '{print $2}'))
LOGFILE="$HOME/.logs/$PROGNAME/$(date +%s%3N)"
mkdir -p $HOME/.logs/$PROGNAME 2> /dev/null

exec 19>$LOGFILE
export BASH_XTRACEFD=19
set -x
