#!/usr/bin/bash
# Author: zent
# File: bright
# Description: set the screen's brightness
# Usage:
#	sudo bright <int:0-100>

set -e

BRIGHTNESS=$1
[ -z $BRIGHTNESS ] && RAWBRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
[ ! -z $BRIGHTNESS ] && RAWBRIGHTNESS=$(($BRIGHTNESS * 1000))
echo "Setting brightness to $RAWBRIGHTNESS ($BRIGHTNESS%)"
echo $RAWBRIGHTNESS > /sys/class/backlight/intel_backlight/brightness
