#!/usr/bin/bash
# Author: zent
# File: devicescreenshot
# Description: Takes a screenshot of a video device. Mostly used for /dev/video (AKA the computer's camera)
# Usage:
#	devicescreenshot /path/to/device

set -e

DEVICE=$1
OUTPATH="$HOME/screenshots"
OUTNAME="$(date -Ins).png"

depend mpv

echo "Saving screenshot from device/file $DEVICE on $OUTPATH/$OUTNAME"
mpv $DEVICE --frames=1 -o $OUTPATH/$OUTNAME > /dev/null && echo "Done" || echo "Failed"
