#!/usr/bin/bash
# Author: zent
# File: finalizegitchanges
# Description: Shortcut for adding, committing and pushing a git repo
# Usage:
#	finalizegitchanges -m "Reason" [-s "Different pass store"]

set -e

depend git
depend pass

POSITIONAL=()
while [[ $# -gt 0 ]]; do
	key="$1"

	case $key in
		-m|--message)
			MESSAGEARG="$2"
			shift
			shift
			;;
		-s|--store)
			STOREARG="$2"
			shift
			shift
			;;
		*)
			POSITIONAL+=("$1")
			shift
			;;
	esac
done

set -- "${POSITIONAL[@]}"
MESSAGEDEF="Default Commit Message"
MESSAGE=${MESSAGEARG:-$MESSAGEDEF}
STOREDEF="github.com"
STORE=${STOREARG:-$STOREDEF}

if [ ! -d ".git" ]; then
	echo "Not a git repository"
	exit -1
fi

read -p "Do you want to finalize your changes to $PWD? [y/N]: " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	echo -n "Adding the changes... " && git add . && echo "Done"
	echo "These are your changes:" && git status && echo "And this is your commit message: $MESSAGE" && read -p "Are you sure you want to commit? [y/N]: " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		echo -n "Committing... " && git commit -m "$MESSAGE" && echo "Done"
		echo "Your password for pushing is: $(pass $STORE)"
		echo -n "Pushing..." && git push -u origin main && echo "Done"
		echo "Finalized changes"
	else
		echo "Got negative response, exiting..."
		exit -2
	fi
else
	echo "Got negative response, exiting..."
	exit -2
fi
