#!/usr/bin/bash
# Author: zent
# File: latestscreenshot
# Description: print the latest screenshot's path
# Usage:
#	latestscreenshot

set -e

source $(which _log)

depend xargs

scrnpath="$1"
[ -z $scrnpath ] && scrnpath="$HOME/screenshots"

/usr/bin/ls "$scrnpath" | tail -n1 | xargs -I {} echo "$scrnpath/{}"
