#!/usr/bin/bash

BACKPWD=$PWD
IFS=':' read -ra SPLITPATH <<< "$PATH"
LIST=("")
for each in "${SPLITPATH[@]}"
do
	LIST+=$(cd $each > /dev/null 2>&1 && ls $each || echo "")
done
cd $BACKPWD
COMMAND=$(( IFS=$'\n'; echo "${LIST[*]}" ) | dmenu)
$COMMAND
