#!/usr/bin/bash
# Author: zent
# File: myip
# Description: fetch the computer's current external IP
# Usage:
#	myip

set -e

depend jq
{ ip route get "1.2.3.4" &> /dev/null; } && { curl -s https://api.myip.com | jq -r .ip; } || { echo "Disconnected"; }
