#!/usr/bin/bash
# Author: zent
# File: readgecos
# Description: Print an user's GECOS comment if present in /etc/passwd
# Usage:
#	readgecos
#	readgecos other-user

set -e

source $(which _log)

user=$([ -z "$1" ] && whoami || echo $1)
echo $user | xargs -I {} grep {} /etc/passwd | awk -F: '{print $5}'
