#!/usr/bin/bash
# Author: zent
# File: reconnectwifi
# Description: Utility script to quickly reconnect to my home wifi with credentials given in enviromental variables
# Usage:
#	reconnectwifi

set -e

depend nmcli

{ [ -n "$WIFINAME" ]; } && { echo "OK"; [ -n "$WIFIPASS" ] && nmcli device wifi connect "$WIFINAME" password "$WIFIPASS" hidden true || nmcli device wifi connect "$WIFINAME" password "$WIFIPASS" || nmcli device wifi connect "$WIFINAME"; } || { echo "NO"; }
