#!/usr/bin/bash
# Author: zent
# File: reloadwal
# Description: Utility script to run pywal on a random wallpaper from the bgs directory
# Usage:
#	reloadwal

set -e

depend wal

wal -i ~/bgs/ --saturate 0.75
