#!/usr/bin/bash

depend herbe

#IP=$(echo $SSH_CONNECTION | awk '{print $1}')
#IP=$(who | awk '{print $5}' | tr -d \(\))      <----Why did I even think this implementation could work lmao?
cd /tmp/.X11-unix
for x in X*; do
	DISPLAY=":${x#X}" herbe "$@" &
done
cd
