#!/usr/bin/bash
# Author: zent
# File: sshherbe
# Description: Display an herbe notification on all X sessions
# Usage:
#	sshherbe "Message"

set -e

depend herbe

cd /tmp/.X11-unix
for x in X*; do
	DISPLAY=":${x#X}" herbe "$@" &
done
cd
