#!/usr/bin/bash
# Author: zent
# File: tunnel
# Description: Tunnel the selected port through ngrok and send the URL over via KDEConnect
# Usage:
#	  tunnel <protocol> <port>

set -e

source $(which _log)

depend kdeconnect-cli
depend nc
depend jq
depend ngrok

DEVICE="4ecff932_801f_4ce9_a847_b7cf73164246"
PROTOCOL="$1"
PORT="$2"

ngrok $PROTOCOL $PORT > /dev/null &
while ! nc -z localhost 4040; do
  sleep 0.5
done

REMOTE="$(curl http://localhost:4040/api/tunnels --silent | jq ".tunnels[0].public_url")"

kdeconnect-cli --ping-msg "Tunnel started at: $REMOTE" --device $DEVICE
kdeconnect-cli --share-text $REMOTE --device $DEVICE
echo "Tunnel started at: $REMOTE"
