#!/usr/bin/bash
# Author: zent
# File: whoishome
# Description: Display all online devices in a give network
# Usage:
#	whoishome
#	whoishome <other.ip.range>

set -e

[ -z $1 ] && IPRANGE="192.168.1.0/25"
[ ! -z $1 ] && CAMERA="$1"

depend nmap
depend awk

echo "Enumerating... "
outnmap=$(nmap -sn -v "$IPRANGE" -oG -)
echo "Done."
echo ""
echo "$outnmap" | awk '/Up$/{print "IP: ", $2, "\tNAME: ", $3}'
